name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: echo ${{ github.event.release.tag_name }} | xargs npm version

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.release.tag_name }}
          force: true
  build:
    needs: release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: macos
            arch: x64
          - os: macos-latest
            platform: macos
            arch: arm64
          - os: windows-latest
            platform: windows
            arch: x64
    env:
      BUILD_PLATFORM: ${{ matrix.platform }}
      BUILD_ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Make build script executable
        run: chmod +x ./buildForRelease.sh

      - name: Build for release
        run: ./buildForRelease.sh -p ${{ env.BUILD_PLATFORM }} -a ${{ env.BUILD_ARCH }} -v ${{ github.event.release.tag_name }}
      
      - name: Upload portable executable
        uses: actions/upload-artifact@v4
        with:
          name: github-action-viewer-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_ARCH }}
          path: |
            build/github-action-viewer*
            !build/*.tar.gz

      - name: Upload release archive
        uses: actions/upload-artifact@v4
        with:
          name: github-action-viewer-archive-${{ env.BUILD_PLATFORM }}-${{ env.BUILD_ARCH }}
          path: build/github-action-viewer-*.tar.gz

  attach-to-release:
    name: Attach Artifacts to Release
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}